OTC-24: Renewal was sent succesfully but does not reflect in the web
openimis/policies_android_app_java pull request #52
Opened 2021-05-10 05:58 UTC by malinowskikam

Changes:
- Addded error handling (`HTTP 401`) to receipt no. check in renewal validation to inform user that he needs to log in first.
- Added additional error handling to `UploadOfflineFeedbackRenewal`
- Fitted `MoveFile` to new filesystem handling
- Changed date format from `yyyyMMdd` to `yyyy-MM-dd` as the first was getting randomly rejected.

Submitting this PR as a draft because there is still a problem in processing a renewal made from a prompt.

2021-06-14 09:31 UTC, dragos-dobre requested changes

2021-06-14 09:31 UTC, dragos-dobre commented on app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
> +                            if (responseCode == 200) {
Please create a const list with HTTP responses and use that instead of actual value (e.g. HTTPResponse.OK).

2021-06-14 09:31 UTC, dragos-dobre commented on app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
> +                    if(response == null || responseCode!=200 || uploadStatus==2)
What does uploadStatus==2 mean? Please create a const list with values (1, 2...) and use that instead of actual value.

2021-06-14 09:31 UTC, dragos-dobre commented on app/src/main/java/org/openimis/imispolicies/ClientAndroidInterface.java
> +                    result = -2;
Please create a const list with values (-2...) and use that instead of actual value to know what the value means.

2021-06-14 09:31 UTC, dragos-dobre commented on app/src/main/java/org/openimis/imispolicies/Renewal.java
> +                    } else if (responseCode == 401) {
Use const instead of 401.

2021-06-14 09:31 UTC, dragos-dobre commented on app/src/main/java/org/openimis/imispolicies/Renewal.java
> +                    if (responseCode == 200) {
Use const instead of 200. Please update everywhere.

2021-06-14 09:31 UTC, dragos-dobre commented on app/src/main/res/values/strings.xml
> +  <string name="ImisDirNotCreated">IMIS Directory could not be created.</string>
Was this added to Lokalize?

2021-06-15 07:20 UTC, malinowskikam commented on app/src/main/res/values/strings.xml
> +  <string name="ImisDirNotCreated">IMIS Directory could not be created.</string>
Yes, I added it.

2021-06-15 09:17 UTC, malinowskikam commented
@dragos-dobre I replaced all HTTP status codes with consts from `java.net` package, and created a static class for REST API response values. It is worth to note that `Claim`, `PolicyRenewal` and `Feedback` repositories use these values, but `Family` repository does not (mainly `uspConsumeEnrollments`).

2021-06-15 15:46 UTC, dragos-dobre approved these changes

2021-06-15 15:46 UTC, merged